// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOScgGGTXF5cJfS-_DVVLXuWVOFIvrZUE',
    appId: '1:61940541937:web:3d117a39ec683feb187c50',
    messagingSenderId: '61940541937',
    projectId: 'el-nor',
    authDomain: 'el-nor.firebaseapp.com',
    storageBucket: 'el-nor.firebasestorage.app',
    measurementId: 'G-RKH4MXFR0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgDgPL325qZacPSAqk4bxxwnTQ6bjB0w',
    appId: '1:61940541937:android:a18b2a89db42c1db187c50',
    messagingSenderId: '61940541937',
    projectId: 'el-nor',
    storageBucket: 'el-nor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDes7u8GfPxXFFamwq-yvs5m_DedoJxoZA',
    appId: '1:61940541937:ios:94b9f0341d993b49187c50',
    messagingSenderId: '61940541937',
    projectId: 'el-nor',
    storageBucket: 'el-nor.firebasestorage.app',
    iosBundleId: 'com.example.beatElslam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDes7u8GfPxXFFamwq-yvs5m_DedoJxoZA',
    appId: '1:61940541937:ios:94b9f0341d993b49187c50',
    messagingSenderId: '61940541937',
    projectId: 'el-nor',
    storageBucket: 'el-nor.firebasestorage.app',
    iosBundleId: 'com.example.beatElslam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOScgGGTXF5cJfS-_DVVLXuWVOFIvrZUE',
    appId: '1:61940541937:web:951dbb656d6088b4187c50',
    messagingSenderId: '61940541937',
    projectId: 'el-nor',
    authDomain: 'el-nor.firebaseapp.com',
    storageBucket: 'el-nor.firebasestorage.app',
    measurementId: 'G-B4VHY9PQJC',
  );
}
